=== ramilmsh-archive/cs308_cell_society/data/Society.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="game">
        <xs:annotation>
            <xs:appinfo>
                Cell Society
            </xs:appinfo>
            <xs:documentation>
                This schema defines initial configuration for a generalized implementation of Cell Society
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>

                <!--Time configuration-->

                <xs:element name="time-unit" type="xs:string" default="seconds" minOccurs="0">
                    <xs:annotation>
                        <xs:appinfo>
                            Time unit
                        </xs:appinfo>
                        <xs:documentation xml:lang="en">
                            Defines default time unit for game
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>

                <xs:element name="step" type="xs:float" default="1.0" minOccurs="0">
                    <xs:annotation>
                        <xs:appinfo>
                            Step
                        </xs:appinfo>
                        <xs:documentation>
                            Defines step size in "time-unit"s
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>

                <xs:element name="finite" type="xs:boolean" default="false" minOccurs="0">
                    <xs:annotation>
                        <xs:appinfo>Time line</xs:appinfo>
                        <xs:documentation>
                            Defines whether the game has finite time-line.
                            If true, must exist end-time
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>

                <xs:element name="end-time" type="xs:float" minOccurs="0">
                    <xs:annotation>
                        <xs:appinfo>
                            End time
                        </xs:appinfo>
                        <xs:documentation>
                            Defines the end time for a finite time line
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>

                <!--util.Cell definition-->

                <xs:element name="cells">
                    <xs:annotation>
                        <xs:appinfo>
                            Cell types
                        </xs:appinfo>
                        <xs:documentation>
                            Defines exiting cell types
                        </xs:documentation>
                    </xs:annotation>

                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cell" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:appinfo>
                                        Cell type
                                    </xs:appinfo>
                                    <xs:documentation>
                                        Defines properties of a cell type
                                    </xs:documentation>
                                </xs:annotation>

                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="symbol">
                                            <xs:simpleType>
                                                <xs:annotation>
                                                    <xs:appinfo>Symbol</xs:appinfo>
                                                    <xs:documentation>
                                                        Symbol to denote cell on the grid
                                                    </xs:documentation>
                                                </xs:annotation>

                                                <xs:restriction>
                                                    <xs:length fixed="true" value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                        <xs:element name="fill" maxOccurs="3">
                                            <xs:annotation>
                                                <xs:appinfo>
                                                    Fill
                                                </xs:appinfo>
                                                <xs:documentation>
                                                    Defines visual representation of the cell
                                                </xs:documentation>
                                            </xs:annotation>

                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="type">
                                                        <xs:simpleType>
                                                            <xs:annotation>
                                                                <xs:appinfo>

                                                                </xs:appinfo>
                                                            </xs:annotation>

                                                            <xs:restriction>
                                                                <xs:enumeration value="SYMBOL"/>
                                                                <xs:enumeration value="COLOR"/>
                                                                <xs:enumeration value="IMAGE"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>

                                                    <xs:element name="content">
                                                        <xs:annotation>
                                                            <xs:appinfo>Content</xs:appinfo>
                                                            <xs:documentation>
                                                                Cell fill:
                                                                - for symbol: char
                                                                - for color: (hex rgb|color name)
                                                                - for image: path to image
                                                            </xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="action" type="xs:string">
                                            <xs:annotation>
                                                <xs:appinfo>Action</xs:appinfo>
                                                <xs:documentation>
                                                    Java class that implements Action interface, located in src/actions
                                                </xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!--util.State definition-->

                <xs:element name="update">
                    <xs:complexType>
                        <xs:annotation>
                            <xs:appinfo>Initial update</xs:appinfo>
                        </xs:annotation>

                        <xs:sequence>
                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:annotation>
                                        <xs:appinfo>State type</xs:appinfo>
                                        <xs:documentation>
                                            Defines initial update type
                                            - random: cells will be generated in random locations, according to
                                            "distribution"
                                            - grid: cells will be generated according to "grid"
                                            -----------
                                            - if grid: "grid" must be defined
                                        </xs:documentation>
                                    </xs:annotation>
                                    <xs:restriction>
                                        <xs:enumeration value="RANDOM"/>
                                        <xs:enumeration value="GRID"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="grid" type="xs:string">
                                <xs:annotation>
                                    <xs:appinfo>Grid</xs:appinfo>
                                    <xs:documentation>
                                        Defines a grid of cells
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="distribution">
                                <xs:complexType>
                                    <xs:annotation>
                                        <xs:appinfo>Cell Distribution</xs:appinfo>
                                        <xs:documentation>
                                            Defines weight distribution of cells

                                            All the values will be considered as relative to total

                                            Any cell not present here will be receive weight of 0
                                        </xs:documentation>
                                    </xs:annotation>
                                    <xs:sequence>
                                        <xs:element name="weight">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:restriction base="xs:float">
                                                        <xs:attribute name="cell" use="required">
                                                            <xs:simpleType>
                                                                <xs:restriction>
                                                                    <xs:length fixed="true" value="1"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:restriction>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="screen-width" type="xs:int" default="400" minOccurs="0">
                                <xs:annotation>
                                    <xs:appinfo>Width</xs:appinfo>
                                    <xs:documentation>
                                        Screen width in pixels
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="screen-height" type="xs:int" default="400" minOccurs="0">
                                <xs:annotation>
                                    <xs:appinfo>Width</xs:appinfo>
                                    <xs:documentation>
                                        Screen height in pixels
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="square" type="xs:boolean" default="true" minOccurs="0">
                                <xs:annotation>
                                    <xs:appinfo>Square</xs:appinfo>
                                    <xs:documentation>
                                        Square or Rectangle
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="max-rows" type="xs:int" default="20" minOccurs="0">
                                <xs:annotation>
                                    <xs:appinfo>Width</xs:appinfo>
                                    <xs:documentation>
                                        Maximum number of rows
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="max-cols" type="xs:int" default="20" minOccurs="0">
                                <xs:annotation>
                                    <xs:appinfo>Width</xs:appinfo>
                                    <xs:documentation>
                                        Maximum number of columns
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ramilmsh-archive/cs308_cell_society/data/Society.sample.xml
<?xml version="1.0" encoding="UTF-8" ?>

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Society.xsd">
    <time-unit>
        seconds
    </time-unit>
    <finite>true</finite>
    <end-time>10000</end-time>
    <cells>
        <cell>
            <symbol>0</symbol>
            <fill>
                <type>COLOR</type>
                <content>red</content>
            </fill>
            <action>Nothing</action>
        </cell>
    </cells>
    <update>
        <type>RANDOM</type>
        <grid>
            01234324
            12312311
            12312312
        </grid>
        <distribution>
            <weight cell="1">.3</weight>
        </distribution>
    </update>
</game>

=== ramilmsh-archive/cs308_cell_society/resources/data/Paper.xml
<?xml version="1.0" encoding="UTF-8"?><game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Society.xsd">
	<cells>
		<cell>
			<symbol>X</symbol>
			<fill>
				<type>COLOR</type>
				<content>blue</content>
			</fill>
			<action>paper.Paper</action>
		</cell>
		<cell>
			<symbol>O</symbol>
			<fill>
				<type>COLOR</type>
				<content>green</content>
			</fill>
			<action>paper.Paper</action>
		</cell>
		<cell>
			<symbol>B</symbol>
			<fill>
				<type>COLOR</type>
				<content>red</content>
			</fill>
			<action>paper.Paper</action>
		</cell>
	</cells>
	<state>
		<type>RANDOM</type>
		<distribution>
			<weight cell="0">0.01</weight>
			<weight cell="O">0.33</weight>
			<weight cell="X">0.33</weight>
			<weight cell="B">0.33</weight>
		</distribution>
	</state></game>

=== ramilmsh-archive/cs308_cell_society/resources/data/gameoflife.xml
<?xml version="1.0" encoding="UTF-8" ?>

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Society.xsd">
    <time-unit>
        seconds
    </time-unit>
    <cells>
        <cell>
            <symbol>A</symbol>
            <fill>
                <type>COLOR</type>
                <content>black</content>
            </fill>
            <action>gameoflife.GameLife</action>
        </cell>
        <cell>
            <symbol>D</symbol>
            <fill>
                <type>COLOR</type>
                <content>white</content>
            </fill>
            <action>gameoflife.GameLife</action>
        </cell>
    </cells>
    <state>
        <type>RANDOM</type>
        <distribution>
            <weight cell="A">.2</weight>
            <weight cell="D">.8</weight>
        </distribution>
    </state>

</game>

=== ramilmsh-archive/cs308_cell_society/resources/data/Society.sample.xml
<?xml version="1.0" encoding="UTF-8" ?>

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Society.xsd">
    <time-unit>
        seconds
    </time-unit>
    <finite>true</finite>
    <end-time>10000</end-time>
    <cells>
        <cell>
            <symbol>1</symbol>
            <fill>
                <type>COLOR</type>
                <content>red</content>
            </fill>
            <action>Test</action>
        </cell>
    </cells>
    <state>
        <type>RANDOM</type>
        <grid>
            01234324
            12312311
            12312312
        </grid>
        <distribution>
            <weight cell="0">.7</weight>
            <weight cell="1">.3</weight>
        </distribution>
    </state>
</game>

=== ramilmsh-archive/cs308_cell_society/resources/data/Segregation.xml
<?xml version="1.0" encoding="UTF-8" ?>

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Society.xsd">
    <time-unit>
        seconds
    </time-unit>
    <cells>
        <cell>
            <symbol>X</symbol>
            <fill>
                <type>COLOR</type>
                <content>red</content>
            </fill>
            <action>segregation.Agent</action>
        </cell>
        <cell>
            <symbol>O</symbol>
            <fill>
                <type>COLOR</type>
                <content>blue</content>
            </fill>
            <action>segregation.Agent</action>
        </cell>
    </cells>
    <state>
        <type>RANDOM</type>
        <distribution>
            <weight cell="0">.5</weight>
            <weight cell="X">.3</weight>
            <weight cell="O">.2</weight>
        </distribution>
    </state>
</game>

=== ramilmsh-archive/cs308_cell_society/resources/data/fire.xml
<?xml version="1.0" encoding="UTF-8" ?>

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Society.xsd">
    <time-unit>
        seconds
    </time-unit>
    <cells>
        <cell>
            <symbol>E</symbol>
            <fill>
                <type>COLOR</type>
                <content>yellow</content>
            </fill>
            <action>fire.Spread</action>
        </cell>
        <cell>
            <symbol>T</symbol>
            <fill>
                <type>COLOR</type>
                <content>green</content>
            </fill>
            <action>fire.Spread</action>
        </cell>
        <cell>
            <symbol>B</symbol>
            <fill>
                <type>COLOR</type>
                <content>red</content>
            </fill>
            <action>fire.Spread</action>
        </cell>
    </cells>
    <state>
        <type>RANDOM</type>
        <distribution>
            <weight cell="E">.03</weight>
            <weight cell="T">.96</weight>
            <weight cell="B">.01</weight>
        </distribution>
    </state>

</game>
